# Generated by Django 2.0.8 on 2018-10-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0004_gallerypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
