# Generated by Django 2.0.8 on 2018-10-17 20:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('owlpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owlpage',
            name='body',
            field=wagtail.core.fields.StreamField([('owl_paragraph', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', template='blocks/paragraph_block.html'))], blank=True, null=True, verbose_name='Описание проекта'),
        ),
    ]
