# Generated by Django 2.0.8 on 2018-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0002_designworkindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='designworkpage',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер по порядку'),
        ),
    ]
