# Generated by Django 2.0.8 on 2018-10-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0008_auto_20181018_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designworkpage',
            options={'verbose_name': 'Дизайн страница', 'verbose_name_plural': 'Дизайн страницы'},
        ),
    ]
