# Generated by Django 2.0.8 on 2018-10-19 09:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0009_auto_20181018_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designworkpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=True)), ('caption', wagtail.core.blocks.CharBlock(label='Описание', required=False)), ('attribution', wagtail.core.blocks.CharBlock(label='др. аттрибуты', required=False)), ('main', wagtail.core.blocks.BooleanBlock(label='показывать первым', required=False))]))], verbose_name='Дополнительные изображения'),
        ),
    ]
