# Generated by Django 2.0.8 on 2018-10-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0010_auto_20181019_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designworkindexpage',
            options={'verbose_name': 'Страница работ с таблицей изображений без перехода', 'verbose_name_plural': 'Авторы'},
        ),
    ]
