# Generated by Django 2.0.8 on 2018-10-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0011_auto_20181019_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designworkindexpage',
            options={'verbose_name': 'Страница работ с таблицей изображений без перехода', 'verbose_name_plural': 'Страницы работ с таблицей изображений без перехода'},
        ),
    ]
