# Generated by Django 2.0.8 on 2018-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_work', '0013_auto_20181022_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='designworkpage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
